# Generated by Django 4.2.3 on 2023-07-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=127, unique=True)),
                ('repository', models.CharField(max_length=255)),
                ('deploy', models.CharField(max_length=255, null=True)),
                ('video', models.CharField(max_length=255, null=True)),
                ('cover', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('highlighted', models.BooleanField(default=False)),
            ],
        ),
    ]
