# Generated by Django 4.2.3 on 2023-07-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
        ('technologies', '0001_initial'),
        ('projects', '0002_project_content_project_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='libs',
            field=models.ManyToManyField(related_name='projects', to='libraries.library'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(related_name='projects', to='technologies.technology'),
        ),
    ]
