# Generated by Django 4.2.3 on 2023-07-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0003_alter_technology_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=127),
        ),
    ]
